name=PfeifferTurboTC80
version=1.0.2
author=Kyle Worcester-Moore
maintainer=Kyle Worcester-Moore
sentence=Control interface for Pfeiffer TC80-driven turbo pumps.
paragraph=Implements the Pfeiffer Vacuum Protocol over RS-485 serial for Pfeiffer turbomolecular pumps driven by a TC80 electronic drive unit allowing controlling and reading parameters of the pump from arduino. It reqires an appropriate RS-485 to TTL converter with DE/RE direction control for Arduino compatibility.  Not endorsed by or affiliated with Pfeiffer Vacuum.
category=Communication
url=https://github.com/Girguis-Lab/PfeifferTurboTC80
architectures=avr
license=MIT
depends=RingBufCPP (>=1.3)
includes=PfeifferTurboTC80.h
